version: 3
workdir: .
allow:
  depOnAnyVendor: false
  deepScan: true

exclude:
  - "examples"

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\/test\/.*$"

vendors:
  kronk-sdk:
    in: "github.com/ardanlabs/kronk/sdk/**"

components:
  agent: { in: agent }
  kronk: { in: kronk }
  llm: { in: llm }
  tui: { in: tui }

deps:

  llm:
    canUse:
      - kronk-sdk

  kronk:
    canUse:
      - kronk-sdk

  agent:
    canUse:
      - kronk-sdk
    mayDependOn:
      - llm

  tui:
    mayDependOn:
      - agent
      - llm
